CREATE DATABASE IF NOT EXISTS LookShare;
USE LookShare;

-- Drop Tables

-- DROP TABLE Accounts;
-- DROP TABLE Posts;
-- DROP TABLE Comments;
-- DROP TABLE Ratings;
-- DROP TABLE Reactions;
-- DROP TABLE Followers;

-- Table Creation

CREATE TABLE Accounts (
	userId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	pinnedPostId INT,
	firstName VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL,
	private BOOL NOT NULL DEFAULT FALSE,
	bio VARCHAR(500),
	bioLink VARCHAR(500)
);

CREATE TABLE Posts (
	postId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	authorId INT NOT NULL,
	parentPostID INT,
	photo BLOB NOT NULL,
	products VARCHAR(150) NOT NULL,
	instructions VARCHAR(500) NOT NULL,
	lookKind VARCHAR(50) NOT NULL,
	lookTime INT NOT NULL,
	lookDifficulty INT NOT NULL,
	time DATETIME NOT NULL DEFAULT now()
);

CREATE TABLE Comments (
	postId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	authorId INT NOT NULL,
	parentPostId INT,
	parentCommentId INT,
	comment VARCHAR(500),
	isRepost BOOL NOT NULL DEFAULT FALSE,
	restricted BOOL NOT NULL DEFAULT FALSE,
	time DATETIME NOT NULL DEFAULT now()
);

CREATE TABLE Ratings (
	ratingId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	authorId INT NOT NULL,
	raterId INT NOT NULL,
	score INT NOT NULL,
	comment VARCHAR(500)
);

CREATE TABLE Reactions (
	parentPostId INT NOT NULL,
	reactorId INT NOT NULL,
	isPositive BOOL NOT NULL DEFAULT TRUE
);

CREATE TABLE Followers (
	leaderId INT NOT NULL,
	followerId INT NOT NULL
);

-- Link Foreign Keys

ALTER TABLE Accounts
	ADD CONSTRAINT
	FOREIGN KEY(pinnedPostId)
	REFERENCES Posts(postId)
	ON UPDATE NO ACTION
	ON DELETE SET NULL;
	
ALTER TABLE Posts
	ADD CONSTRAINT
	FOREIGN KEY(authorId)
	REFERENCES Accounts(userId)
	ON UPDATE NO ACTION
	ON DELETE CASCADE,
	
	ADD CONSTRAINT
	FOREIGN KEY(parentPostId)
	REFERENCES Posts(postId)
	ON UPDATE NO ACTION
	ON DELETE SET NULL;

ALTER TABLE Comments
	ADD CONSTRAINT
	FOREIGN KEY(authorId)
	REFERENCES Accounts(userId)
	ON UPDATE NO ACTION
	ON DELETE CASCADE,
	
	ADD CONSTRAINT
	FOREIGN KEY(parentPostId)
	REFERENCES Posts(postId)
	ON UPDATE NO ACTION
	ON DELETE SET NULL,
	
	ADD CONSTRAINT
	FOREIGN KEY(parentCommentId)
	REFERENCES Comments(postId)
	ON UPDATE NO ACTION
	ON DELETE SET NULL;

ALTER TABLE Ratings
	ADD CONSTRAINT
	FOREIGN KEY(authorId)
	REFERENCES Accounts(userId)
	ON UPDATE NO ACTION
	ON DELETE CASCADE,
	
	ADD CONSTRAINT
	FOREIGN KEY(raterId)
	REFERENCES Accounts(userId)
	ON UPDATE NO ACTION
	ON DELETE CASCADE;

ALTER TABLE Reactions
	ADD CONSTRAINT
	FOREIGN KEY(parentPostId)
	REFERENCES Posts(postId)
	ON UPDATE NO ACTION
	ON DELETE CASCADE,
	
	ADD CONSTRAINT
	FOREIGN KEY(reactorId)
	REFERENCES Accounts(userId)
	ON UPDATE NO ACTION
	ON DELETE CASCADE;
	
ALTER TABLE Followers
	ADD CONSTRAINT
	FOREIGN KEY(leaderId)
	REFERENCES Accounts(userId)
	ON UPDATE NO ACTION
	ON DELETE CASCADE,
	
	ADD CONSTRAINT
	FOREIGN KEY(followerId)
	REFERENCES Accounts(userId)
	ON UPDATE NO ACTION
	ON DELETE CASCADE;
